/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNI_Test */

#ifndef _Included_JNI_Test
#define _Included_JNI_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNI_Test
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNI_1Test_print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
